In [1]:
import numpy as np

In [7]:
arr1 = np.array(10)

In [12]:
np.arange(1,100,step=4,dtype='float')

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45., 49.,
       53., 57., 61., 65., 69., 73., 77., 81., 85., 89., 93., 97.])

In [18]:
np.linspace(1,100,num=150)

array([  1.        ,   1.66442953,   2.32885906,   2.99328859,
         3.65771812,   4.32214765,   4.98657718,   5.65100671,
         6.31543624,   6.97986577,   7.6442953 ,   8.30872483,
         8.97315436,   9.63758389,  10.30201342,  10.96644295,
        11.63087248,  12.29530201,  12.95973154,  13.62416107,
        14.2885906 ,  14.95302013,  15.61744966,  16.28187919,
        16.94630872,  17.61073826,  18.27516779,  18.93959732,
        19.60402685,  20.26845638,  20.93288591,  21.59731544,
        22.26174497,  22.9261745 ,  23.59060403,  24.25503356,
        24.91946309,  25.58389262,  26.24832215,  26.91275168,
        27.57718121,  28.24161074,  28.90604027,  29.5704698 ,
        30.23489933,  30.89932886,  31.56375839,  32.22818792,
        32.89261745,  33.55704698,  34.22147651,  34.88590604,
        35.55033557,  36.2147651 ,  36.87919463,  37.54362416,
        38.20805369,  38.87248322,  39.53691275,  40.20134228,
        40.86577181,  41.53020134,  42.19463087,  42.85

In [19]:
import pandas as pd

In [22]:
arr2 = pd.array([1,2,3,4,5,6])

In [24]:
arr2.shape

(6,)

In [31]:
ser1 = pd.Series([1,2,3,4,5,6],index=['row1','row2','row3','row4','row5','row6'])

In [33]:
ser1.index

Index(['row1', 'row2', 'row3', 'row4', 'row5', 'row6'], dtype='object')

In [34]:
ser1.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [35]:
ser1.row3

3

In [36]:
ser1["row2"]

2